### ISSUE TITLE
:align: center doesn't work

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/sphinx_materialdesign_theme#9]
From what I can tell, the `:align: center;` doesn't work on an `.. image` (and probably else where).

```rst
.. image:: image.png
    :align: center
```

This seems to be because the `:align: center;` adds the following css;
```css
.align-center, .align-default {
    margin-left: auto!important;
    margin-right: auto!important;
}
```

However a `.img` is an inline element so the `margin-left: auto; margin-right: auto;` trick doesn't work.

This seems to be fixed by applying the `display: block` css to the element.
